import localFont from 'next/font/local';
import { NextIntlClientProvider } from 'next-intl';
import { getMessages, setRequestLocale } from 'next-intl/server';
import { notFound } from 'next/navigation';
import "../globals.css"
import Header from '@/components/core/Header';
import Footer from '@/components/core/Footer';

const poppins = localFont({
  src: [
    { path: '../../public/fonts/Poppins-Thin.ttf', weight: '100', style: 'normal' },
    { path: '../../public/fonts/Poppins-ExtraLight.ttf', weight: '200', style: 'normal' },
    { path: '../../public/fonts/Poppins-Light.ttf', weight: '300', style: 'normal' },
    { path: '../../public/fonts/Poppins-Regular.ttf', weight: '400', style: 'normal' },
    { path: '../../public/fonts/Poppins-Medium.ttf', weight: '500', style: 'normal' },
    { path: '../../public/fonts/Poppins-SemiBold.ttf', weight: '600', style: 'normal' },
    { path: '../../public/fonts/Poppins-Bold.ttf', weight: '700', style: 'normal' },
    { path: '../../public/fonts/Poppins-ExtraBold.ttf', weight: '800', style: 'normal' },
    { path: '../../public/fonts/Poppins-Black.ttf', weight: '900', style: 'normal' },
  ],
  variable: '--font-poppins',
});

export async function generateMetadata({ params: { locale } }) {
  return {
    title: "Cervision",
    description: "Generated by Cervision",
  };
}

export default async function RootLayout({ children, params: { locale } }) {
  let messages;
  try {
    messages = (await import(`../../messages/${locale}.json`)).default;
  } catch (error) {
    notFound();
  }

  return (
    <html lang={locale}>
      <head>
         <meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover" />
        <meta name="theme-color" content="#ffffff" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className={`${poppins?.variable || ""} antialiased`}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <div className="min-h-screen flex flex-col">
            <Header />
            <main className="flex-1">{children}</main>
            <Footer />
          </div>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}